-- MySQL Script generated by MySQL Workbench
-- seg 11 abr 2022 20:33:47
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pessoa` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `primeiroNome` VARCHAR(30) NOT NULL,
  `sobrenome` VARCHAR(70) NOT NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `bairro` VARCHAR(30) NULL,
  `numero` INT(4) UNSIGNED NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `complemento` VARCHAR(30) NULL,
  PRIMARY KEY (`idPessoa`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefone`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefone` (
  `idPessoa` INT NOT NULL,
  `fone` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idPessoa`, `fone`),
  CONSTRAINT `idPessoa`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `email` VARCHAR(40) NOT NULL,
  `totalGasto` DECIMAL(8,2) UNSIGNED NOT NULL,
  `pedidosEfetuados` INT(4) UNSIGNED NOT NULL,
  PRIMARY KEY (`idCliente`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Loja`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Loja` (
  `idLoja` INT NOT NULL,
  `cnpj` VARCHAR(14) NOT NULL,
  `nome` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(8) NOT NULL,
  `rua` VARCHAR(50) NOT NULL,
  `numero` INT(4) UNSIGNED NOT NULL,
  `bairro` VARCHAR(30) NULL,
  `cidade` VARCHAR(30) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  `qtdFuncionarios` INT(4) NULL,
  `totalVendido` DECIMAL(12,2) NULL,
  `produtosVendidos` INT(9) NULL,
  PRIMARY KEY (`idLoja`),
  UNIQUE INDEX `cnpj_UNIQUE` (`cnpj` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funcionario` (
  `idFuncionario` INT NOT NULL,
  `regFuncionario` VARCHAR(4) NOT NULL,
  `salario` DECIMAL(6,2) NOT NULL,
  `idLoja` INT NOT NULL,
  PRIMARY KEY (`idFuncionario`),
  UNIQUE INDEX `registro_UNIQUE` (`regFuncionario` ASC) VISIBLE,
  INDEX `idLoja_idx` (`idLoja` ASC) VISIBLE,
  CONSTRAINT `idFuncionario`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `mydb`.`Pessoa` (`idPessoa`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `idLoja`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`Loja` (`idLoja`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Motorista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motorista` (
  `idMotorista` INT NOT NULL,
  `regCNH` VARCHAR(11) NOT NULL,
  `habilitacao` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idMotorista`),
  UNIQUE INDEX `regCNH_UNIQUE` (`regCNH` ASC) VISIBLE,
  CONSTRAINT `idMotorista`
    FOREIGN KEY (`idMotorista`)
    REFERENCES `mydb`.`Funcionario` (`idFuncionario`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VeiculoEntrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VeiculoEntrega` (
  `idVeiculo` INT NOT NULL,
  `idMotorista` INT NULL,
  `placa` VARCHAR(7) NOT NULL,
  `tipoVeiculo` VARCHAR(15) NOT NULL,
  `cilindradas` INT(4) NULL,
  `capacidadePeso` DECIMAL(2,1) NULL,
  PRIMARY KEY (`idVeiculo`),
  INDEX `idMotorista_idx` (`idMotorista` ASC) VISIBLE,
  UNIQUE INDEX `placa_UNIQUE` (`placa` ASC) VISIBLE,
  CONSTRAINT `idMotorista`
    FOREIGN KEY (`idMotorista`)
    REFERENCES `mydb`.`Motorista` (`idMotorista`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pedido` (
  `numPedido` INT NOT NULL,
  `idCliente` INT NULL,
  `idLoja` INT NULL,
  `codEntrega` VARCHAR(11) NOT NULL,
  `idVeiculo` INT NOT NULL,
  `valor` DECIMAL(7,2) NOT NULL,
  `data` DATETIME NOT NULL,
  `distanciaEntrega` DECIMAL(4,1) NOT NULL,
  PRIMARY KEY (`numPedido`),
  INDEX `idCliente_idx` (`idCliente` ASC) VISIBLE,
  INDEX `idLoja_idx` (`idLoja` ASC) VISIBLE,
  INDEX `idVeiculo_idx` (`idVeiculo` ASC) VISIBLE,
  UNIQUE INDEX `codEntrega_UNIQUE` (`codEntrega` ASC) VISIBLE,
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `idLoja`
    FOREIGN KEY (`idLoja`)
    REFERENCES `mydb`.`Loja` (`idLoja`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `idVeiculo`
    FOREIGN KEY (`idVeiculo`)
    REFERENCES `mydb`.`VeiculoEntrega` (`idVeiculo`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `codProduto` VARCHAR(14) NOT NULL,
  `preco` DECIMAL(6,2) NOT NULL,
  `nome` VARCHAR(30) NOT NULL,
  UNIQUE INDEX `codProduto_UNIQUE` (`codProduto` ASC) VISIBLE,
  PRIMARY KEY (`codProduto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produtos-Pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produtos-Pedido` (
  `numPedido` INT NOT NULL,
  `codProduto` VARCHAR(14) NOT NULL,
  `quantidade` INT(5) UNSIGNED NOT NULL,
  `precoVendido` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`codProduto`, `numPedido`),
  CONSTRAINT `numPedido`
    FOREIGN KEY (`numPedido`)
    REFERENCES `mydb`.`Pedido` (`numPedido`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `codProduto`
    FOREIGN KEY (`codProduto`)
    REFERENCES `mydb`.`Produto` (`codProduto`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
